/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.37.0
  Forc version: 0.35.3
  Fuel-Core version: 0.17.3
*/

export type { MyCounterProjectAbi } from './MyCounterProjectAbi';

export { MyCounterProjectAbi__factory } from './factories/MyCounterProjectAbi__factory';
